general.import = ["~/.config/alacritty/hyper.toml"]

[[keyboard.bindings]]
key = "F11"
command = "fullscreen"  # 'wmctrl -ir $(xdotool getwindowfocus) -b toggle,fullscreen'

[font]
size = 11.0

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "UbuntuMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[scrolling]
history = 100000
multiplier = 3

[window]
# false causes alacritty to not use the system theme in some cases (?)
dynamic_title = true
